timeout: 60
port: ":8887"
load_balance_mode: "rand"
reverse_host:
  - {service_name: "test"}
etcd:
  username: ""
  password: ""
  endpoints: ["127.0.0.1:2379"]
  dial_timeout: 5
  dial_keepalive_timeout: 5
  dial_keepalive_time: 30
  local_cache_default_expiration: 10
  local_cache_clean_up_time: 60